version: "3"

volumes:
  config:
    external: true
  cacheData:
    external: true

services:
  site:
    restart: unless-stopped
    build: ./site
    container_name: site
    volumes:
      - config:/config
    ports:
      - 8090:8090

  cache:
    restart: unless-stopped
    image: redis:7.0.7-alpine
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - cacheData:/data
    container_name: Cache