version: "3"

volumes:
  config:
    external: true
  cacheData:
    external: true
  dbData:
    external: true
    
services:
  api:
    restart: unless-stopped
    build: ./apiSrc
    container_name: api
    depends_on:
      - postgres
      - cache
    volumes:
      - config:/config
    ports:
      - 8090:8090

  cache:
    restart: unless-stopped
    image: redis:7.0.7-alpine
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - cacheData:/data
    container_name: Cache

  postgres:
      restart: unless-stopped
      image: postgres:15.2-alpine
      environment:
        - POSTGRES_USER=disstat
        - POSTGRES_PASSWORD=AQwrMb4WzngykR9v
        - POSTGRES_DB=disstat
      ports:
        - 5436:5432
      volumes:
        - ./schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
        - dbData:/var/lib/postgresql/data
      container_name: DB
      
  site:
    restart: unless-stopped
    build: ./siteSrc
    container_name: site
    depends_on:
      - api
    ports:
      - 80:80